import { test, expect } from '@playwright/test';

// E2E test: Ensure session page renders correct UI based on ?mode query param
// If TEST_SESSION_ID is not seeded, global-setup should handle creation.

// Use authenticated user state generated by global-setup

// The ID of the session seeded in the global E2E setup.
// TODO: Consider reading from env or a shared helper. For now use the same hard-coded ID as other E2E suites.
const TEST_SESSION_ID = 'clxnt1o60000008l3f9j6g9z7';

test.describe('Session Page Mode Switching', () => {
  test.use({ storageState: 'tests/e2e/storageState.json' });

  test('renders TextInterviewUI by default', async ({ page }) => {
    await page.goto(`/sessions/${TEST_SESSION_ID}`);
    await expect(page.getByTestId('text-interview-ui')).toBeVisible();
  });

  test('renders VoiceInterviewUI when mode=voice', async ({ page }) => {
    await page.goto(`/sessions/${TEST_SESSION_ID}?mode=voice`);
    await expect(page.getByTestId('voice-interview-ui')).toBeVisible();
  });
}); 